version: "3.8"

services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/src
      - /src/node_modules
    environment:
      - NODE_ENV=development
    restart: always
