export const mockData = {
  dash: "예식장",
  item: [
    {
      id: 1,
      title: "부모님 메이크업 업체 선정",
      assignee: "신랑",
      date: "2025.01.29",
      state: true,
      amount: "1,000,000",
    },
    {
      id: 2,
      title: "예식장 예약하기",
      assignee: "신부",
      date: "2025.01.02",
      state: true,
      amount: "1,000,000",
    },
    {
      id: 3,
      title: "부모님 메이크업 업체 선정",
      assignee: "신랑",
      date: "2025.01.09",
      state: true,
      amount: "1,000,000",
    },
    {
      id: 4,
      title: "부모님 메이크업 업체 선정",
      assignee: "신랑",
      date: "2025.01.29",
      state: false,
      amount: "1,000,000",
    },
    {
      id: 5,
      title: "부모님 메이크업 업체 선정",
      assignee: "신랑",
      date: "2025.01.29",
      state: false,
    },
    {
      id: 6,
      title: "부모님 메이크업 업체 선정",
      assignee: "신랑",
      date: "2025.01.29",
      state: false,
    },
  ],
};